sdk:
sdkversion: 2.0.0
name: store
version: 1.0
vendor: rhomobile
build: debug
applog: rholog.txt
bbver: 6.0
iphone:
  configuration: Debug
  sdk: iphonesimulator4.0
  emulator: 4.0.1
  provisionprofile:
  codesignidentity:
  entitlements:
extensions: ["json"]

android:
  version: 2.2

wp:
  productid: '1aa73f88-4d47-4f94-acdd-ab9301d45a2a'