sdk:
sdkversion: 2.0.0
name: store
version: 1.0
vendor: rhomobile
build: debug
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator3.0
  provisionprofile:
  codesignidentity:
  entitlements:
extensions: ["json"]
