sources:
  Customer:
    source_id: 1
    url: http://example.com
    login: 
    password: 
    poll_interval: 300
    partition_type: app
    sync_type: incremental
  Product:
    source_id: 2
    url: http://example.com
    login: 
    password: 
    poll_interval: 300
    partition_type: user
    sync_type: bulk_sync_only